name: Release

on:
  workflow_dispatch:

jobs:
  release-packages:
    name: Release DEB & RPM Package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies & FPM
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential cmake libtool python3 \
                                  ruby ruby-dev rubygems rpm libssl-dev
          sudo gem install --no-document fpm

      - name: Set env variables
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "ITERATION=$(cat ITERATION)" >> $GITHUB_ENV

      - name: Build
        run: |
          git clone --depth 1 -b v${{ env.VERSION }} https://github.com/apache/kvrocks.git
          cd kvrocks
          ./x.py build -DPORTABLE=1 -DCMAKE_BUILD_TYPE=Release -j $(nproc)

      - name: Prepare Packaging RootFS
        run: |
          mkdir -p rootfs/usr/bin
          mkdir -p rootfs/etc/kvrocks
          mkdir -p rootfs/usr/lib/systemd/system
          mkdir -p rootfs/var/lib/kvrocks
          mkdir -p rootfs/var/log/kvrocks
          mkdir -p rootfs/usr/share/doc/kvrocks

          # Binaries
          cp kvrocks/build/kvrocks rootfs/usr/bin/
          cp kvrocks/build/kvrocks2redis rootfs/usr/bin/

          # Configuration
          cp kvrocks/kvrocks.conf rootfs/etc/kvrocks/kvrocks.conf

          # Systemd service unit
          cp kvrocks/utils/systemd/kvrocks.service rootfs/usr/lib/systemd/system/

          # License & Notice
          cp -r kvrocks/LICENSE kvrocks/NOTICE kvrocks/licenses rootfs/usr/share/doc/kvrocks/

      - name: Package DEB
        run: |
          fpm -s dir -t deb \
            -n kvrocks \
            -v "${{ env.VERSION }}" \
            --iteration "${{ env.ITERATION }}" \
            -a amd64 \
            -C rootfs \
            --config-files /etc/kvrocks/kvrocks.conf \
            --after-install scripts/postinst.sh \
            --after-remove scripts/postrm.sh \
            --description 'A distributed key value NoSQL database that uses RocksDB as storage engine and is compatible with Redis protocol' \
            --url 'https://kvrocks.apache.org' \
            --license 'Apache-2.0' \
            -p "kvrocks_${{ env.VERSION }}-${{ env.ITERATION }}_amd64.deb"

      - name: Package RPM
        run: |
          fpm -s dir -t rpm \
            -n kvrocks \
            -v "${{ env.VERSION }}" \
            --iteration "${{ env.ITERATION }}" \
            -a x86_64 \
            -C rootfs \
            --config-files /etc/kvrocks/kvrocks.conf \
            --after-install scripts/postinst.sh \
            --after-remove scripts/postrm.sh \
            --description 'A distributed key value NoSQL database that uses RocksDB as storage engine and is compatible with Redis protocol' \
            --url 'https://kvrocks.apache.org' \
            --license 'Apache-2.0' \
            -p "kvrocks-${{ env.VERSION }}-${{ env.ITERATION }}.x86_64.rpm"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}-${{ env.ITERATION }}"
          name: "${{ env.VERSION }}-${{ env.ITERATION }}"
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
